### ISSUE TITLE
Create a MinIO plugin

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-aws#144]
Create a dedicated plugin for MinIO.

The following task will not work on MinIO S3-compatible object storage.

```yaml
  - id: play_minio
    type: io.kestra.plugin.aws.s3.List 
    accessKeyId: <accessKeyId>
    bucket: test1
    endpointOverride: https://play.min.io:9000/
    region: us-east-1
    secretKeyId: <secretKeyId>
```

It generates an `UnknownHostException test1.play.min.io`.

Therefore, we should create a new plugin that will mimic the existing S3 tasks. For example: 

- io.kestra.plugin.aws.s3.List -> io.kestra.plugin.minio.List 
- io.kestra.plugin.aws.s3.Upload -> io.kestra.plugin.minio.Upload 
- io.kestra.plugin.aws.s3.Download -> io.kestra.plugin.minio.Download 
- io.kestra.plugin.aws.s3.Downloads -> io.kestra.plugin.minio.Downloads 
- io.kestra.plugin.aws.s3.CreateBucket -> io.kestra.plugin.minio.CreateBucket
