### ISSUE TITLE
Mark all properties of the DynamoDB `PutItem` task except for the `item` as ignorable

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#180]
### Expected Behavior

This example using `taskDefaults` cannot be saved:

```yaml
id: addItemToDynamoDB
namespace: blueprint
tasks:
  - id: firstItemAsMap
    type: io.kestra.plugin.aws.dynamodb.PutItem
    item:
      id: 1
      flow: "{{ flow.id }}"
      task: "{{ task.id }}"

  - id: secondItemAsJSON
    type: io.kestra.plugin.aws.dynamodb.PutItem
    item: |
        {
            "id": 2,
            "flow": "{{ flow.id }}",
            "task": "{{ task.id }}"
        }

taskDefaults:
  - type: io.kestra.plugin.aws.dynamodb.PutItem
    tableName: demo
    region: eu-central-1
    accessKeyId: "{{envs.aws_access_key_id}}"
    secretKeyId: "{{envs.aws_secret_access_key}}"
```

### Actual Behaviour

Error:

```
Unrecognized field "tableName" (class io.kestra.core.models.flows.TaskDefault), 
not marked as ignorable (3 known properties: "forced", "type", "values"])
```

The same happens with all other attributes of that task.

Only explicitly specifying all attributes works atm:

```yaml
id: addItemToDynamoDB
namespace: blueprint
tasks:
  - id: firstItemAsMap
    type: io.kestra.plugin.aws.dynamodb.PutItem
    tableName: demo
    region: eu-central-1
    accessKeyId: "{{envs.aws_access_key_id}}"
    secretKeyId: "{{envs.aws_secret_access_key}}"
    item:
      id: 1
      flow: "{{ flow.id }}"
      task: "{{ task.id }}"

  - id: secondItemAsJSON
    type: io.kestra.plugin.aws.dynamodb.PutItem
    tableName: demo
    region: eu-central-1
    accessKeyId: "{{envs.aws_access_key_id}}"
    secretKeyId: "{{envs.aws_secret_access_key}}"
    item: |
        {
            "id": 2,
            "flow": "{{ flow.id }}",
            "task": "{{ task.id }}"
        }
```

### Environment Information

- Kestra Version: develop-full image

**Comment by tchiotludo** [comment]
You are wrong on the `taskDefaults` syntax:  
```yaml
taskDefaults:
  - type: io.kestra.plugin.aws.dynamodb.PutItem
    values: 
      tableName: demo
      region: eu-central-1
      accessKeyId: "{{envs.aws_access_key_id}}"
      secretKeyId: "{{envs.aws_secret_access_key}}"
```
