### ISSUE TITLE
Allow adding System-defined object metadata to the S3 upload task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#214]
### Feature description

A simple reproducer where the AWS CLI task will result in the proper `Content-Type` system-defined metadata:
![image](https://github.com/kestra-io/plugin-aws/assets/86264395/354129d1-53f7-431b-be50-1b39b352967d)

and the s3.Upload task will give:
![image](https://github.com/kestra-io/plugin-aws/assets/86264395/ed3d50bc-4753-4ade-96db-cead90a518e0)

```yaml
id: s3
namespace: tmp
tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: html
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          index.html: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Kestra flow page</title>
            </head>
            <body>
                <header>
                    <h1>Hello world</h1>
                </header>
            </body>
            </html>

      - id: cli
        type: io.kestra.plugin.aws.cli.AwsCLI
        region: "{{ secret('AWS_DEFAULT_REGION') }}"
        accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
        secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
        commands:
          - aws s3 cp {{workingDir}}/index.html s3://kestraio/index3.html --content-type text/html

      - id: htmlOut
        type: io.kestra.core.tasks.storages.LocalFiles
        outputs:
          - "*.html"

      - id: upload
        type: io.kestra.plugin.aws.s3.Upload
        bucket: kestraio
        from: "{{outputs.htmlOut.uris['index.html']}}"
        key: index2.html
        metadata:
          Content-Type: text/html
        region: "{{ secret('AWS_DEFAULT_REGION') }}"
        accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
        secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
```
