### ISSUE TITLE
Return an empty list if no objects found under a given S3 prefix

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#220]
Reproducer:

```yaml
id: ingestToDataLake
namespace: blueprint

variables:
  bucket: kestraio

tasks:
  - id: listObjects
    type: io.kestra.plugin.aws.s3.List
    bucket: kestraio
    prefix: inbox
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ secret('AWS_DEFAULT_REGION') }}"

  - id: checkObjects
    type: io.kestra.core.tasks.flows.If
    condition: "{{outputs.listObjects.objects}}"
```

If there are no S3 objects under the `inbox` path, the task should return an empty list rather than returning no outputs.
