### ISSUE TITLE
Add Amazon EventBridge`PutEvents` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#236]
### Feature description

This issue is for now only about adding the `PutEvents` task. Here is how it works from the CLI: assuming that you have the following file named `event.json` (see [detailed schema here](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEventsRequestEntry.html#eventbridge-Type-PutEventsRequestEntry-Resources))

```json
[
    {
        "DetailType": "event-bridge",
        "Source": "kestra",
        "EventBusName": "default",
        "Detail": "{\"message\": \"hello from Event Bridge and CLI\"}"
    }
]
```

You can send custom events to Event Bridge using the command: 

```bash
aws events put-events --entries file://event.json
```

The detail type and source properties will need to match the Event Patterns configured on a specific EventBridge Rule to initiate some event-driven action (AWS forwards those events to up to 5 targets). However, you can send events even without having any matching rules. So this task, for now, is only to send events using [the `PutEvents` API](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html) sent with [Java SDK](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/eventbridge/EventBridgeClient.html#putRule) 

"`Detail`, `DetailType`, and `Source` are required for EventBridge to successfully send an event to an event bus. If you include event entries in a request that do not include each of those properties, EventBridge fails that entry. If you submit a request in which none of the entries have each of these properties, EventBridge fails the entire request."

## Proposed syntax

```yaml
id: aws_event_bridge
namespace: dev

tasks:
  - id: PutEvents
    type: io.kestra.plugin.aws.eventbridge.PutEvents
    entries:
      - source: kestra # required string
        eventBusName: default # optional string
        detailType: event-bridge # required string
        detail: # required JSON string but we should make it a map to ensure user passes a proper map format
          message: hello EventBridge from Kestra
        resources: # optional array of strings
          - string
```
