### ISSUE TITLE
Add a `GetAuthToken` task for ECR

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#268]
### Feature description

Currently, to push or pull ECR images, users need to follow quite a complex CLI syntax that will output the token and pass it to another task:

```yaml
id: pythonAwsECR
namespace: blueprint

tasks:
  - id: aws
    type: io.kestra.plugin.aws.cli.AwsCLI
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: eu-central-1
    commands:
      - TOKEN=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 --decode | cut -d':' -f2)
      - echo "::{\"outputs\":{\"token\":\"$TOKEN\"}}::"

  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    docker:
      image: 338306982838.dkr.ecr.eu-central-1.amazonaws.com/data-infastructure:latest
      config: |
        {
          "auths": {
            "338306982838.dkr.ecr.eu-central-1.amazonaws.com": {
                "username": "AWS",
                "password": "{{outputs.aws.vars.token}}"
              }
          }
        }
    commands:
      - python --version # e.g. python yourscript.py
```

## New task

Add a task to make that process easier. The syntax might be similar to:

```yaml
id: ecr
namespace: dev

tasks:
  - id: auth
    type: io.kestra.plugin.aws.ecr.GetAuthToken
    outputVariable: token
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: eu-central-1

  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    docker:
      image: 338306982838.dkr.ecr.eu-central-1.amazonaws.com/data-infastructure:latest
      config: |
        {
          "auths": {
            "338306982838.dkr.ecr.eu-central-1.amazonaws.com": {
                "username": "AWS",
                "password": "{{outputs.auth.vars.token}}"
              }
          }
        }
    commands:
      - python --version # e.g. python yourscript.py
```
