### ISSUE TITLE
AWS SQS Consume fetches record in a weird format

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-aws#360]
### Expected Behavior

AWS SQS Consume should be able to fetch the rows from the SQS queue, and have the fetched records noted as a single column with 1 record per row.

### Actual Behaviour

The records are fetched from the SQS queue as 1 record per row, but each character in the record is put in a separate column. I have attached the screenshot for better understanding.

![Screenshot 2024-01-28 at 6 49 43 PM](https://github.com/kestra-io/plugin-aws/assets/6594483/915723b2-b48d-4e3c-bcbe-409dcf1324b7)

### Steps To Reproduce

1. Use the sample flow as mentioned in the [page](https://kestra.io/plugins/plugin-aws/tasks/sqs/io.kestra.plugin.aws.sqs.Consume) with appropriate access key, secret key and queueUrl. Also add maxRecords to the flow. 
2. Produce records in the queue (equal or more than the number of maxrRecords).
3. Execute the flow.

### Environment Information

- Kestra Version: 0.13.8
- Plugin version: 0.13.8
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```yaml
id: "consume"
type: "io.kestra.plugin.aws.sqs.Consume"
accessKeyId: "<access-key>"
secretKeyId: "<secret-key>"
region: "eu-central-1"
queueUrl: "https://sqs.eu-central-1.amazonaws.com/000000000000/test-queue"
maxRecords: 2
```
