### ISSUE TITLE
Output files are not captured yet in AWS Batch Script Runner

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#405]
### Feature description

they are captured but empty

is:
![image](https://github.com/kestra-io/plugin-aws/assets/86264395/8e605629-57f6-4984-914b-702224aaf191)
should be:
![image](https://github.com/kestra-io/plugin-aws/assets/86264395/588c84d1-4375-4caa-ab9b-b9b6e8b20739)

repro:

```yaml
id: aws_batch_output_files
namespace: dev

tasks:
  - id: send_data
    type: io.kestra.plugin.scripts.python.Commands
    containerImage: ghcr.io/kestra-io/pydata:latest
    scriptRunner:
      type: io.kestra.plugin.aws.runner.AwsBatchScriptRunner
      region: "eu-central-1"
      accessKeyId: aaa
      secretKeyId: aaa
      computeEnvironmentArn: "arn:aws:batch:eu-central-1:707969873520:compute-environment/kestraFargateEnvironment"
      jobQueueArn: "arn:aws:batch:eu-central-1:707969873520:job-queue/kestraJobQueue"
      executionRoleArn: "arn:aws:iam::707969873520:role/kestraEcsTaskExecutionRole"
      taskRoleArn: arn:aws:iam::707969873520:role/ecsTaskRole
      s3Bucket: kestra-product-de
    commands:
      - python {{workingDir}}/main.py
      - ls
      - cat {{workingDir}}/environment_info.json > {{outputDir}}/environment_info.json
    outputFiles:
      - "environment_info.json"
    inputFiles:
      main.py: |
        import platform
        import socket
        import sys
        import json 
        from kestra import Kestra

        print("Hello from AWS Batch and kestra!")

        def print_environment_info():
            print(f"Host's network name: {platform.node()}")
            print(f"Python version: {platform.python_version()}")
            print(f"Platform information (instance type): {platform.platform()}")
            print(f"OS/Arch: {sys.platform}/{platform.machine()}")

            env_info = {
                "host": platform.node(),
                "platform": platform.platform(),
                "OS": sys.platform,
                "python_version": platform.python_version(),
            }
            Kestra.outputs(env_info)

            filename = 'environment_info.json'
            with open(filename, 'w') as json_file:
                json.dump(env_info, json_file, indent=4)

        print_environment_info()
```
