### ISSUE TITLE
Add support for Regex pattern in `outputFiles` in AwsBatchTaskRunner

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#415]
### Feature description

Example showing the pattern `*.json`:

```yaml
id: python_etl
namespace: dev

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://dummyjson.com/products

  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:3.11-alpine 
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json"
    env:
      COLUMNS_TO_KEEP: "{{ inputs.columns_to_keep }}"
    script: |
      import json

      columns_to_keep = ["brand", "price"]

      with open("data.json", "r") as file:
          data = json.load(file)

      filtered_data = [
          {column: product[column] for column in columns_to_keep}
          for product in data["products"]
      ]
      with open("products.json", "w") as file:
          json.dump(filtered_data, file, indent=4)
```
