### ISSUE TITLE
[Likely front-end/display issue] Fix Output Preview on SQS trigger

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#456]
### Expected Behavior

when you send a text message, kestra will currently try to parse it as ION - likely better to treat it as a text file or json file

![image](https://github.com/kestra-io/plugin-aws/assets/86264395/707282f1-4a07-417d-93f9-df1ff71f0b25)

![image](https://github.com/kestra-io/plugin-aws/assets/86264395/acd0b2d1-d318-41c6-95ec-b4eb2440acbf)

reproducer:
```yaml
id: sqs
namespace: release

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger }}"

triggers:
  - id: sqs_batch
    type: io.kestra.plugin.aws.sqs.Trigger
    queueUrl: https://sqs.eu-west-1.amazonaws.com/707969873520/release
    maxRecords: 1
    interval: PT1S
```

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
