### ISSUE TITLE
SQS trigger didn't trigger when there are less messages available than maxRecords

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-aws#529]
### Expected Behavior

SQS trigger triggers and execution when there are less messages available than maxRecords

### Actual Behaviour

When we push messages to the queue that it is listening to, as long as there are equal to or more messages than what is specified in "maxRecords" our flow executes successfully. If there are fewer, the messages are consumed from the SQS queue but there is never a flow execution for the trigger and messages just disappear.

```yaml
id: pollForNewFiles
disabled: false
type: io.kestra.plugin.aws.sqs.Trigger
maxRecords: 5
serdeType: JSON
queueUrl: "{{ vars.queueUrl }}"
interval: 30
```

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
