### ISSUE TITLE
Plugin Defaults not working correctly on s3 Upload/Download

### ISSUE THREAD

**Issue by MarthaScheffler** [kestra-io/plugin-aws#546]
### Expected Behavior

It should be possible to use pluginDefaults on the io.kestra.plugin.aws.S3 tasks.

### Actual Behaviour

- using 'bucket' in PluginDefaults generates an error and doesn't even allow me to save the code
- using credentials and region in PluginDefaults, the code executes, but AWS replies with a 403

the code runs when I add all info in the task itself

### Environment Information

- Kestra Version: 19.5
- Operating System (OS / Docker / Kubernetes): k8s

### Example flow

````
id: test_s3
namespace: kestra.s3

pluginDefaults:

  - type: io.kestra.plugin.aws.S3
    values:
      accessKeyId: "{{ secret('KESTRA_IAM_ACCESS_KEY') }}"
      secretKeyId: "{{ secret('KESTRA_IAM_SECRET_KEY') }}"
      region: "eu-north-1"
      bucket: "my_bucket"

tasks:

  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://github.com/kestra-io/scripts/archive/refs/heads/main.zip

  - id: upload_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    #accessKeyId: "{{ secret('KESTRA_IAM_ACCESS_KEY') }}"
    #secretKeyId: "{{ secret('KESTRA_IAM_SECRET_KEY') }}"
    #region: "eu-north-1"
    bucket: "my_bucket"
    from: "{{ outputs.download.uri }}"
    key: "test.zip"

  - id: download_from_s3
    type: io.kestra.plugin.aws.s3.Download
    #accessKeyId: "{{ secret('KESTRA_IAM_ACCESS_KEY') }}"
    #secretKeyId: "{{ secret('KESTRA_IAM_SECRET_KEY') }}"
    #region: "eu-north-1"
    bucket: "my_bucket"
    key: "test.zip"
````

**Comment by anna-geller** [comment]
thx a lot for the issue Maria!

Can you briefly try one of the following, or both:
1. Change to `s3` instead of `S3`
2. add `forced: true`

```yaml
pluginDefaults:
  - type: io.kestra.plugin.aws.s3
    forced: true
    values:
      accessKeyId: "{{ secret('KESTRA_IAM_ACCESS_KEY') }}"
      secretKeyId: "{{ secret('KESTRA_IAM_SECRET_KEY') }}"
      region: "eu-north-1"
      bucket: "my_bucket"
```

might be either an issue of some plugin defaults not being enforced unless used with `forced: true` or an issue with the plugin path you shared using capitalized class name instead of `s3`
