### ISSUE TITLE
Getting "Status 407: Pull failed due to an unauthenticated request..." when using "io.kestra.plugin.aws.cli.AwsCLI"

### ISSUE THREAD

**Issue by oleksii-suprun** [kestra-io/plugin-aws#553]
### Describe the issue

I have an S3 bucket with files partitioned by date and country. I want to check if files are available for the current date and return the list of available prefixes. When files do not exist, then wait for 5 minutes. I implemented a very straightforward workflow for that.

```
id: test_flow
namespace: test

labels:
  owner: me
  environment: local
  project: test

inputs:
  - id: startDate
    type: DATE
    required: false

tasks:
  - id: waitForFiles
    type: io.kestra.plugin.core.flow.WaitFor
    condition: "{{ outputs.listObjects.vars.prefixes | length > 0 }}"
    failOnMaxReached: true
    checkFrequency:
      interval: "PT5M"
      maxIterations: 3
    tasks:
      - id: listObjects
        type: io.kestra.plugin.aws.cli.AwsCLI
        accessKeyId: "XXXXX"
        secretKeyId: "XXXXX"
        region: "us-east-1"
        commands:
          - >-
            aws s3api list-objects-v2 \
              --bucket 'my-bucket' \
              --prefix 'files/date={{ trigger.date ?? inputs.startDate ?? execution.startDate | date('yyyy-MM-dd') }}/' \
              --delimiter '/' \
              --query 'reverse(CommonPrefixes[].[Prefix])' \
              --output 'text' \
             | sed 's/^/"/g' | sed 's/$/"/g' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/' \
             | xargs -0 -I {} echo '::{"outputs":{"prefixes":{}}}::'
```

I tried to use `io.kestra.plugin.aws.s3.List`, and it works fine, but I have more than 1000 files, and I don't want to implement logic to extract common prefixes. That's why CLI solutions work better for me.

I run Kestra locally using Docker Compose, and the latest available config file from here: https://github.com/kestra-io/kestra/blob/develop/docker-compose.yml. 

I deploy my flow with the CLI and Docker container:
```
docker run --rm --network host --entrypoint "/bin/bash" -v $(pwd)/flows:/app/flows kestra/kestra ./kestra flow namespace update test flows/ --server http://localhost:8080
```

But during the attempt to trigger flow from the UI, it fails with the following error:
```
kestra-1    | 2024-11-11 21:06:32,872 ERROR WorkerThread f.d.7.3t8TpEhQV1c2GJjOfBiyOi Status 407: Pull failed due to an unauthenticated request. Registry Access Management is enabled, which requires pulls to be authenticated. Please run `docker login`, or contact your administrators if this is unexpected.
kestra-1    | 
kestra-1    | com.github.dockerjava.api.exception.DockerException: Status 407: Pull failed due to an unauthenticated request. Registry Access Management is enabled, which requires pulls to be authenticated. Please run `docker login`, or contact your administrators if this is unexpected.
kestra-1    | 
kestra-1    | 	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:249)
kestra-1    | 	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
kestra-1    | 	at java.base/java.lang.Thread.run(Unknown Source)
```

I would appreciate any help you can give me.

### Environment

- Kestra Version: 0.19.9
- Docker Desktop: 4.35.1 (173168) 
- MacOS: 14.7.1 (23H222)
