### ISSUE TITLE
Add a task to start AWS Glue job and poll for its completion status

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#586]
### Feature description

When you initiate an AWS Glue job using the `StartJobRun` API, it returns immediately with a unique `JobRunId`, while the job continues to execute asynchronously. To monitor the job's progress and determine its completion status, we can periodically check the job's status by invoking the `GetJobRun` API with the `JobName` and the returned `JobRunId`. This API provides details about the job run, including its current state, which can be one of: STARTING, RUNNING, SUCCEEDED, FAILED, etc. 

API endpoints: 
- https://docs.aws.amazon.com/glue/latest/webapi/API_StartJobRun.html
- https://docs.aws.amazon.com/glue/latest/webapi/API_GetJobRun.html

To create job first if it doesn't exist https://docs.aws.amazon.com/glue/latest/webapi/API_CreateJob.html 

Java client: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/glue/AWSGlueClient.html

Example flow syntax:

```yaml
id: aws_glue
namespace: company.team

tasks:
  - id: start
    type: io.kestra.plugin.aws.glue.StartJobRun
    wait: true
    checkFrequency: # optional
      maxIterations: 100
      maxDuration: 3600
      interval: 100
```

**Comment by KhalefAhmed** [comment]
Hi @anna-geller
I'd like to work on this feature

**Comment by anna-geller** [comment]
You got it! Thanks in advance!

**Comment by MilosPaunovic** [comment]
Hey @KhalefAhmed, any updates on this?

**Comment by KhalefAhmed** [comment]
> Hey [@KhalefAhmed](https://github.com/KhalefAhmed), any updates on this?

I've almost finished it I'll be able to open a pull request tomorrow morning when I'll have answers to my questions I'll ask them here when I have a bit of time
here's my branch https://github.com/KhalefAhmed/plugin-aws/tree/ISSUE-586

**Comment by KhalefAhmed** [comment]
Hi @MilosPaunovic  @anna-geller
I propose this task 
```yaml
id: aws_glue
namespace: company.team

tasks:
  - id: start
    type: io.kestra.plugin.aws.glue.StartJobRun
    jobName: my-glue-job
    timeout: 3600
    wait: true
    interval: 100
```
- No need for maxIterations when we already have timeout and interval. The maximum number of iterations is simply timeout/interval and I don't quite understand the relevance of this field

- and also I put `timeout` instead of `maxDuration` because you can define a timeout in the sdk api via StartJobRunRequest
- if you set wait to true, the default interval is 100ms, otherwise you can modify it, knowing that the timeout is defined in minutes.


I want to have your opinions ?
